module.exports = {
  menus:[
    {
      title:'File',
      items:[
        {
          title:"New Project",
          method:function(){
            Project.new();
          }
        },
        {
          title:"Save",
          method:function(){
            Project.save();
          }
        },
        {
          title:"Save As",
          method:function(){
            Project.saveas();
          }
        },
        {
          title:"Load Project",
          method:function(){
            Project.load();
          }
        }
      ]
    },
    {
      title:'Edit',
      items:[
        {
          title:"Project Settings",
          method:function(){
            Project.settings();
          }
        }
      ]
    },
    {
      title:'View',
      items:[
        {
          title:"Layout",
          method:function(){
            Project.layout();
          }
        }
      ]
    },
    {
      title:'Debug',
      items:[
        {
          title:"Console",
          method:function(){
            Project.debug();
          }
        }
      ]
    }
  ],
  toolbar_icons:[
    {
      right:58,
      title:'Minimize',
      src:'/Assets/img/icons/minimize.svg',
      method:function(){
        Win.minimize();
      }
    },
    {
      right:33,
      title:'Maximize',
      src:'/Assets/img/icons/maximize.svg',
      method:function(){
        Win.maximize();
      }
    },
    {
      right:10,
      title:'Close',
      src:'/Assets/img/icons/close.svg',
      method:function(){
        Win.close();
      }
    }
  ]
}
